---
  .travis.yml:
    hc_secure: "yIITEOMfZwv8KfdCxnaO/uXZb1xvxVIvkrIezAyVX+KgOvm/GZr/UqP7vDUSKObPYARTXKA1MTcuKiyGnEDyy0dS3hb6dQgJz2zaauXusUdylCLA/okfEQGyGV+pryFzruCJ30mOTaTgsQICGgFQHyUQ5me68FBdhQ8MSVUlj6E="

